optuna:
  n_trials: 50

model:
  backbone: "resnet50"
  num_classes: 10 # x + 1 (background)

training:
  batch_size: 16
  epochs: 20
  save_dir: "./checkpoints"
  learning_rate: 0.001
  optimizer: "adam"
  scheduler: "step"
  step_size: 10
  gamma: 0.1

dataset:
  path: "/dataset/data"
  train_split: 0.8
